$schema: 'https://moonrepo.dev/schemas/tasks.json'

tasks:
  format-content:
    command: 'prettier --check "**/*.{md,yml,yaml,json,jsonc}"'
    options:
      cache: false
      runInCI: true
      runFromWorkspaceRoot: true

  format-content-fix:
    command: 'prettier --write "**/*.{md,yml,yaml,json,jsonc}"'
    options:
      cache: false
      runInCI: false
      runFromWorkspaceRoot: true
