$schema: 'https://moonrepo.dev/schemas/tasks.json'

tasks:
  typecheck:
    command: 'tsc --noEmit'
    options:
      cache: true
      runInCI: true

  lint:
    command: 'eslint --cache --cache-location .eslintcache .'
    options:
      cache: true
      runInCI: true

  lint-fix:
    command: 'eslint --cache --cache-location .eslintcache --fix .'
    options:
      cache: true

  format:
    command: 'prettier --check "**/*.{ts,tsx,js,jsx,mts,cts}"'
    options:
      cache: false
      runInCI: true

  format-fix:
    command: 'prettier --write "**/*.{ts,tsx,js,jsx,mts,cts}"'
    options:
      cache: false
      runInCI: false

  test:
    command: 'bun test'
    options:
      cache: false
      runInCI: true

  validate:
    deps:
      - typecheck
      - lint
      - format
      - test
