$schema: 'https://moonrepo.dev/schemas/v2/tasks.json'

inheritedBy:
  languages: ['typescript']

tasks:
  typecheck:
    command: 'bun'
    args: ['x', 'tsc', '--project', 'tsconfig.typecheck.json', '--noEmit']
    inputs:
      - '**/*.{ts,tsx,mts,cts,d.ts}'
      - 'tsconfig.json'
      - 'tsconfig.typecheck.json'
      - 'package.json'
      - '/configs/typescript/tsconfig.base.json'
    options:
      cache: true
      runInCI: true

  lint:
    command: 'eslint'
    args: ['.', 'package.json']
    inputs:
      - '**/*.{ts,tsx,js,jsx,mts,cts,svelte}'
      - 'package.json'
      - '/tooling/eslint/base.config.mjs'
      - '/eslint.config.mjs'
    options:
      cache: true
      runInCI: true

  lint-fix:
    command: 'eslint'
    args: ['--fix', '.', 'package.json']
    inputs:
      - '**/*.{ts,tsx,js,jsx,mts,cts,svelte}'
      - 'package.json'
    options:
      cache: false

  format:
    command: 'prettier'
    args: ['--check', '**/*.{ts,tsx,js,jsx,mts,cts,svelte}', '--no-error-on-unmatched-pattern']
    inputs:
      - '**/*.{ts,tsx,js,jsx,mts,cts,svelte}'
      - '/prettier.config.mjs'
      - '/.prettierignore'
    options:
      cache: true
      runInCI: true

  format-fix:
    command: 'prettier'
    args: ['--write', '**/*.{ts,tsx,js,jsx,mts,cts,svelte}', '--no-error-on-unmatched-pattern']
    inputs:
      - '**/*.{ts,tsx,js,jsx,mts,cts,svelte}'
      - '/prettier.config.mjs'
      - '/.prettierignore'
    options:
      cache: false
      runInCI: false

  test:
    command: 'vitest'
    args: ['run', '--passWithNoTests']
    options:
      cache: false
      runInCI: true

  fix:
    deps:
      - lint-fix
      - format-fix
    options:
      runInCI: false

  validate:
    deps:
      - typecheck
      - lint
      - format
      - test
