$schema: 'https://moonrepo.dev/schemas/v2/tasks.json'

inheritedBy:
  languages: ['typescript', 'javascript']

tasks:
  typecheck:
    command: 'tsc --noEmit'
    inputs:
      - '**/*.{ts,tsx,mts,cts}'
      - 'tsconfig.json'
      - '/configs/typescript/tsconfig.base.json'
    options:
      cache: true
      runInCI: true

  lint:
    command: 'eslint .'
    inputs:
      - '**/*.{ts,tsx,js,jsx,mts,cts,svelte}'
      - '/tooling/eslint/base.config.mjs'
      - '/eslint.config.mjs'
    options:
      cache: true
      runInCI: true

  lint-fix:
    command: 'eslint --fix .'
    inputs:
      - '**/*.{ts,tsx,js,jsx,mts,cts,svelte}'
    options:
      cache: false

  format:
    command: 'prettier --check "**/*.{ts,tsx,js,jsx,mts,cts,svelte}"'
    inputs:
      - '**/*.{ts,tsx,js,jsx,mts,cts,svelte}'
      - '/prettier.config.mjs'
      - '/.prettierignore'
    options:
      cache: true
      runInCI: true

  format-fix:
    command: 'prettier --write "**/*.{ts,tsx,js,jsx,mts,cts,svelte}"'
    inputs:
      - '**/*.{ts,tsx,js,jsx,mts,cts,svelte}'
    options:
      cache: false
      runInCI: false

  test:
    command: 'vitest run --passWithNoTests'
    options:
      cache: false
      runInCI: true

  fix:
    deps:
      - lint-fix
      - format-fix
    options:
      runInCI: false

  validate:
    deps:
      - typecheck
      - lint
      - format
      - test
