$schema: 'https://moonrepo.dev/schemas/tasks.json'

tasks:
  typecheck:
    command: 'tsc --noEmit'
    inputs:
      - '**/*.{ts,tsx,mts,cts}'
      - 'tsconfig.json'
    options:
      cache: true
      runInCI: true

  lint:
    command: 'eslint .'
    inputs:
      - '**/*.{ts,tsx,js,jsx,mts,cts}'
    options:
      cache: true
      runInCI: true

  lint-fix:
    command: 'eslint --fix .'
    inputs:
      - '**/*.{ts,tsx,js,jsx,mts,cts}'
    options:
      cache: false

  format:
    command: 'prettier --check "**/*.{ts,tsx,js,jsx,mts,cts}"'
    inputs:
      - '**/*.{ts,tsx,js,jsx,mts,cts}'
    options:
      cache: true
      runInCI: true

  format-fix:
    command: 'prettier --write "**/*.{ts,tsx,js,jsx,mts,cts}"'
    inputs:
      - '**/*.{ts,tsx,js,jsx,mts,cts}'
    options:
      cache: false
      runInCI: false

  test:
    command: 'bun test'
    options:
      cache: false
      runInCI: true

  fix:
    deps:
      - lint-fix
      - format-fix
    options:
      runInCI: false

  validate:
    deps:
      - typecheck
      - lint
      - format
      - test
